openapi: 3.0.1
info:
  title: GestaoVoos
  description: API Definition of RegistroManutencao
  version: 1.0.0
servers:
- url: http://localhost:8290/insert
paths:
  /opInsertProblema:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /opInsertTarefas:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /InsertPecasManutencao:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /notificacao/{id_manutencao}:
    get:
      parameters:
      - name: id_manutencao
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
